Add error handling for missing token

diff --git a/repo-reaper b/repo-reaper
--- a/repo-reaper
+++ b/repo-reaper
@@ -102,6 +102,17 @@ done
 # Verify Inputs #
 #################
 
+# If GITHUB_TOKEN wasn't set in Environment
+if [[ -z ${GITHUB_TOKEN} ]]; then
+  echo "ERROR: GITHUB_TOKEN was not found in your environment. You must export "
+  echo "this token prior to running the script."
+  echo "  Ex: EXPORT GITHUB_TOKEN=abc123def456"
+  echo ""
+  echo "Exiting script with no changes."
+  echo ""
+  exit 1
+fi
+
 # If ORG_NAME wasn't passed
 if [[ -z ${ORG_NAME} ]]; then
   echo "ERROR: ORG_NAME was not provided."
